services:
  kafka-901:
    image: apache/kafka:${KAFKA_VERSION}
    container_name: kafka-901
    environment:
      KAFKA_NODE_ID: 901
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://kafka-901:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:SASL_SSL
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL: PLAIN
      KAFKA_LISTENER_NAME_CONTROLLER_PLAIN_SASL_JAAS_CONFIG: org.apache.kafka.common.security.plain.PlainLoginModule required username="controller_user" password="controller_secret" user_controller_user="controller_secret" user_broker_user="broker_secret";
      KAFKA_SSL_KEYSTORE_LOCATION: /opt/kafka/security/kafka-901.keystore.jks
      KAFKA_SSL_TRUSTSTORE_LOCATION: /opt/kafka/security/kafka-901.truststore.jks
      KAFKA_SSL_KEYSTORE_PASSWORD: kafka-labs
      KAFKA_SSL_KEY_PASSWORD: kafka-labs
      KAFKA_SSL_TRUSTSTORE_PASSWORD: kafka-labs
      KAFKA_CONTROLLER_QUORUM_VOTERS: 901@kafka-901:9093,902@kafka-902:9093,903@kafka-903:9093
      KAFKA_LOG_DIRS: /opt/kafka/data
    volumes:
      - ./security/data/kafka-901-creds:/opt/kafka/security:ro
    healthcheck:
      test: nc -z kafka-901 9093
      interval: 2s
      timeout: 2s
      retries: 3
      start_period: 2s

  kafka-902:
    image: apache/kafka:${KAFKA_VERSION}
    container_name: kafka-902
    environment:
      KAFKA_NODE_ID: 902
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://kafka-902:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:SASL_SSL
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL: PLAIN
      KAFKA_LISTENER_NAME_CONTROLLER_PLAIN_SASL_JAAS_CONFIG: org.apache.kafka.common.security.plain.PlainLoginModule required username="controller_user" password="controller_secret" user_controller_user="controller_secret" user_broker_user="broker_secret";
      KAFKA_SSL_KEYSTORE_LOCATION: /opt/kafka/security/kafka-902.keystore.jks
      KAFKA_SSL_TRUSTSTORE_LOCATION: /opt/kafka/security/kafka-902.truststore.jks
      KAFKA_SSL_KEYSTORE_PASSWORD: kafka-labs
      KAFKA_SSL_KEY_PASSWORD: kafka-labs
      KAFKA_SSL_TRUSTSTORE_PASSWORD: kafka-labs
      KAFKA_CONTROLLER_QUORUM_VOTERS: 901@kafka-901:9093,902@kafka-902:9093,903@kafka-903:9093
      KAFKA_LOG_DIRS: /opt/kafka/data
    volumes:
      - ./security/data/kafka-902-creds:/opt/kafka/security:ro
    healthcheck:
      test: nc -z kafka-902 9093
      interval: 2s
      timeout: 2s
      retries: 3
      start_period: 2s

  kafka-903:
    image: apache/kafka:${KAFKA_VERSION}
    container_name: kafka-903
    environment:
      KAFKA_NODE_ID: 903
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://kafka-903:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:SASL_SSL
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL: PLAIN
      KAFKA_LISTENER_NAME_CONTROLLER_PLAIN_SASL_JAAS_CONFIG: org.apache.kafka.common.security.plain.PlainLoginModule required username="controller_user" password="controller_secret" user_controller_user="controller_secret" user_broker_user="broker_secret";
      KAFKA_SSL_KEYSTORE_LOCATION: /opt/kafka/security/kafka-903.keystore.jks
      KAFKA_SSL_TRUSTSTORE_LOCATION: /opt/kafka/security/kafka-903.truststore.jks
      KAFKA_SSL_KEYSTORE_PASSWORD: kafka-labs
      KAFKA_SSL_KEY_PASSWORD: kafka-labs
      KAFKA_SSL_TRUSTSTORE_PASSWORD: kafka-labs
      KAFKA_CONTROLLER_QUORUM_VOTERS: 901@kafka-901:9093,902@kafka-902:9093,903@kafka-903:9093
      KAFKA_LOG_DIRS: /opt/kafka/data
    volumes:
      - ./security/data/kafka-903-creds:/opt/kafka/security:ro
    healthcheck:
      test: nc -z kafka-903 9093
      interval: 2s
      timeout: 2s
      retries: 3
      start_period: 2s

  kafka-101:
    image: apache/kafka:${KAFKA_VERSION}
    container_name: kafka-101
    ports:
      - "9192:9092"
    environment:
      KAFKA_NODE_ID: 101
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: PLAINTEXT://kafka-101:9092,REPLICATION://kafka-101:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-101:9092,REPLICATION://kafka-101:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:SASL_SSL,REPLICATION:SASL_SSL,PLAINTEXT:PLAINTEXT
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL: PLAIN
      KAFKA_LISTENER_NAME_CONTROLLER_PLAIN_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"broker_user\" password=\"broker_secret\";"
      KAFKA_LISTENER_NAME_REPLICATION_PLAIN_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"broker_user\" password=\"broker_secret\" user_broker_user=\"broker_secret\";"
      KAFKA_SSL_KEYSTORE_LOCATION: /opt/kafka/security/kafka-101.keystore.jks
      KAFKA_SSL_TRUSTSTORE_LOCATION: /opt/kafka/security/kafka-101.truststore.jks
      KAFKA_SSL_KEYSTORE_PASSWORD: kafka-labs
      KAFKA_SSL_KEY_PASSWORD: kafka-labs
      KAFKA_SSL_TRUSTSTORE_PASSWORD: kafka-labs
      KAFKA_CONTROLLER_QUORUM_VOTERS: 901@kafka-901:9093,902@kafka-902:9093,903@kafka-903:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: REPLICATION
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_LOG_DIRS: /opt/kafka/data
    volumes:
      - ./security/data/kafka-101-creds:/opt/kafka/security:ro
    healthcheck:
      test: nc -z kafka-101 9092
      interval: 2s
      timeout: 2s
      retries: 3
      start_period: 2s
    depends_on:
      kafka-901:
        condition: service_healthy
      kafka-902:
        condition: service_healthy
      kafka-903:
        condition: service_healthy

  kafka-102:
    image: apache/kafka:${KAFKA_VERSION}
    container_name: kafka-102
    ports:
      - "9292:9092"
    environment:
      KAFKA_NODE_ID: 102
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: PLAINTEXT://kafka-102:9092,REPLICATION://kafka-102:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-102:9092,REPLICATION://kafka-102:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:SASL_SSL,REPLICATION:SASL_SSL,PLAINTEXT:PLAINTEXT
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL: PLAIN
      KAFKA_LISTENER_NAME_CONTROLLER_PLAIN_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"broker_user\" password=\"broker_secret\";"
      KAFKA_LISTENER_NAME_REPLICATION_PLAIN_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"broker_user\" password=\"broker_secret\" user_broker_user=\"broker_secret\";"
      KAFKA_SSL_KEYSTORE_LOCATION: /opt/kafka/security/kafka-102.keystore.jks
      KAFKA_SSL_TRUSTSTORE_LOCATION: /opt/kafka/security/kafka-102.truststore.jks
      KAFKA_SSL_KEYSTORE_PASSWORD: kafka-labs
      KAFKA_SSL_KEY_PASSWORD: kafka-labs
      KAFKA_SSL_TRUSTSTORE_PASSWORD: kafka-labs
      KAFKA_CONTROLLER_QUORUM_VOTERS: 901@kafka-901:9093,902@kafka-902:9093,903@kafka-903:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: REPLICATION
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_LOG_DIRS: /opt/kafka/data
    volumes:
      - ./security/data/kafka-102-creds:/opt/kafka/security:ro
    healthcheck:
      test: nc -z kafka-102 9092
      interval: 2s
      timeout: 2s
      retries: 3
      start_period: 2s
    depends_on:
      kafka-901:
        condition: service_healthy
      kafka-902:
        condition: service_healthy
      kafka-903:
        condition: service_healthy

  kafka-103:
    image: apache/kafka:${KAFKA_VERSION}
    container_name: kafka-103
    ports:
      - "9392:9092"
    environment:
      KAFKA_NODE_ID: 103
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: PLAINTEXT://kafka-103:9092,REPLICATION://kafka-103:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-103:9092,REPLICATION://kafka-103:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:SASL_SSL,REPLICATION:SASL_SSL,PLAINTEXT:PLAINTEXT
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL: PLAIN
      KAFKA_LISTENER_NAME_CONTROLLER_PLAIN_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"broker_user\" password=\"broker_secret\";"
      KAFKA_LISTENER_NAME_REPLICATION_PLAIN_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"broker_user\" password=\"broker_secret\" user_broker_user=\"broker_secret\";"
      KAFKA_SSL_KEYSTORE_LOCATION: /opt/kafka/security/kafka-103.keystore.jks
      KAFKA_SSL_TRUSTSTORE_LOCATION: /opt/kafka/security/kafka-103.truststore.jks
      KAFKA_SSL_KEYSTORE_PASSWORD: kafka-labs
      KAFKA_SSL_KEY_PASSWORD: kafka-labs
      KAFKA_SSL_TRUSTSTORE_PASSWORD: kafka-labs
      KAFKA_CONTROLLER_QUORUM_VOTERS: 901@kafka-901:9093,902@kafka-902:9093,903@kafka-903:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: REPLICATION
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_LOG_DIRS: /opt/kafka/data
    volumes:
      - ./security/data/kafka-103-creds:/opt/kafka/security:ro
    healthcheck:
      test: nc -z kafka-103 9092
      interval: 2s
      timeout: 2s
      retries: 3
      start_period: 2s
    depends_on:
      kafka-901:
        condition: service_healthy
      kafka-902:
        condition: service_healthy
      kafka-903:
        condition: service_healthy

  akhq:
    image: tchiotludo/akhq:${AKHQ_VERSION}
    container_name: akhq
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka-101:9092,kafka-102:9092,kafka-103:9092"
              schema-registry:
                url: "http://schema-registry:8081"
              connect:
                - name: connect
                  url: "http://connect:8083"
    ports:
      - 8085:8080
    restart: always
    depends_on:
      kafka-101:
        condition: service_healthy