---
- name: Create super users
  hosts: localhost

  tasks:
    - name: Update apt cache and install Docker dependencies
      ansible.builtin.apt:
        name:
          - docker-compose
          - python3-docker
        state: present
        update_cache: yes
      become: yes

    - name: Stop services from docker-compose.yaml
      community.docker.docker_compose:
        project_src: /workspaces/kafka-labs-admin
        state: absent

    - name: Change KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND to true in docker-compose.yaml
      ansible.builtin.replace:
        path: /workspaces/kafka-labs-admin/docker-compose.yaml
        regexp: 'KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND:\s*"?false"?'
        replace: 'KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"'

    - name: Start services from docker-compose.yaml
      community.docker.docker_compose:
        project_src: /workspaces/kafka-labs-admin
        state: present

    - name: Wait until admin is configured
      ansible.builtin.shell: docker logs create-users
      register: create_users_logs
      until: '"Completed updating config for user admin." in create_users_logs.stdout'
      retries: 30
      delay: 2

    - name: Stop services from docker-compose.yaml
      community.docker.docker_compose:
        project_src: /workspaces/kafka-labs-admin
        state: absent

    - name: Change KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND to false in docker-compose.yaml
      ansible.builtin.replace:
        path: /workspaces/kafka-labs-admin/docker-compose.yaml
        regexp: 'KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND:\s*"?true"?'
        replace: 'KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "false"'