---
- name: Start docker-compose
  hosts: localhost

  tasks:
    - name: Update apt cache and install Docker dependencies
      ansible.builtin.apt:
        name:
          - docker-compose
          - python3-docker
        state: present
        update_cache: yes
      become: yes

    - name: Start services from docker-compose.yaml
      community.docker.docker_compose:
        project_src: /workspaces/kafka-labs
        state: present