---
- name: Prepare Kafka upgrade
  hosts: localhost

  tasks:
    - name: Update apt cache and install Docker dependencies
      ansible.builtin.apt:
        name:
          - docker-compose
          - python3-docker
        state: present
        update_cache: yes
      become: yes

    - name: Stop services from docker-compose.yaml
      community.docker.docker_compose:
        project_src: /workspaces/kafka-labs-admin
        state: absent

    - name: Change KAFKA_VERSION to 3.9
      ansible.builtin.replace:
        path: /workspaces/kafka-labs-admin/.env
        regexp: '^KAFKA_{{ item }}_VERSION=.*$'
        replace: 'KAFKA_{{ item }}_VERSION=3.9.1'
      loop:
        - 901
        - 902
        - 903
        - 101
        - 102
        - 103

    - name: Change KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND to true
      ansible.builtin.replace:
        path: /workspaces/kafka-labs-admin/.env
        regexp: '^KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND=.*$'
        replace: 'KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND=true'

    - name: Start services from docker-compose.yaml
      community.docker.docker_compose:
        project_src: /workspaces/kafka-labs-admin
        state: present