---
- name: Run Kafka upgrade
  hosts: localhost

  tasks:
    - name: Upgrade Kafka controllers
      include_tasks: upgrade-single-kafka-broker.yml
      vars:
        kafka_id: "{{ item }}"
        version: "4.0.0"
        start_message: "Our registration has been persisted to the metadata log"
      loop:
        - 901
        - 902
        - 903

    - name: Upgrade Kafka brokers
      include_tasks: upgrade-single-kafka-broker.yml
      vars:
        kafka_id: "{{ item }}"
        version: "4.0.0"
        start_message: "Kafka Server started"
      loop:
        - 101
        - 102
        - 103