---
- name: Publish Schemas
  hosts: localhost
  become: no

  tasks:
    - name: Execute the publishSchema.sh script
      ansible.builtin.shell:
        cmd: ./publishSchema.sh
        chdir: /workspaces/kafka-labs/code/dotnet/Shared.Contracts
      args:
        executable: /bin/bash
      register: registry_result
      until: registry_result.rc == 0
      retries: 10
      delay: 6
