{
 "title": "Kafka Consumers / Fetch Rate & Records Lag",
 "tags": [
  "kafka",
  "clients"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "env",
    "query": {
     "query": "label_values(org_apache_kafka_consumer_fetch_manager_records_consumed_rate,env)"
    }
   },
   {
    "name": "topic",
    "label": "topic",
    "query": {
     "query": "label_values(org_apache_kafka_consumer_fetch_manager_records_consumed_rate,topic)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Consumer Client Lag",
   "type": "timeseries",
   "description": "The latest lag of each client",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(org_apache_kafka_consumer_fetch_manager_records_lag{env=\"$env\", topic=\"$topic\"}) by(topic, group_id, client_instance_id)",
     "legendFormat": "{{group_id}} ({{client_instance_id}})"
    }
   ]
  },
  {
   "title": "Fetch Bytes Per Request",
   "type": "timeseries",
   "description": "The average number of bytes fetched per request for a topic",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "org_apache_kafka_consumer_fetch_manager_fetch_size_avg{env=\"$env\", topic=\"$topic\"}",
     "legendFormat": "{{client_id}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Consumed Bytes Rate Per Second",
   "type": "timeseries",
   "description": "The average number of bytes consumed per second",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "org_apache_kafka_consumer_fetch_manager_bytes_consumed_rate{env=\"$env\", topic=\"$topic\"}",
     "legendFormat": "{{client_id}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Consumed Records Rate Per Second",
   "type": "timeseries",
   "description": "The average number of records consumed per second",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "org_apache_kafka_consumer_fetch_manager_records_consumed_rate{env=\"$env\", topic=\"$topic\"}",
     "legendFormat": "{{client_id}} ({{instance}})"
    }
   ]
  }
 ]
}