{
 "title": "Kafka / Brokers JVM & OS",
 "description": "Java Virtual Machine Memory and OS metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Env",
    "query": {
     "query": "label_values(kafka_jvm_os_OpenFileDescriptorCount,env)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "JVM Memory Used (Non-Heap)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"nonheap\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used (Heap)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "GC Process Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{gc=\"G1 Young Generation\"}[5m]) \r\n/ \r\nrate(jvm_gc_collection_seconds_count{gc=\"G1 Young Generation\"}[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "kafka_jvm_os_SystemCpuLoad{env=\"$env\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Process CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "kafka_jvm_os_ProcessCpuLoad{env=\"$env\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_jvm_os_OpenFileDescriptorCount{env=\"$env\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Free Physical Memory",
   "type": "timeseries",
   "description": "The amount of free physical memory in bytes.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kafka_jvm_os_FreePhysicalMemorySize{env=\"$env\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Available Virtual Memory",
   "type": "timeseries",
   "description": "The amount of virtual memory that is guaranteed to be available to the running process in bytes",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kafka_jvm_os_CommittedVirtualMemorySize{env=\"$env\"}",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}