{
 "title": "Kafka Cluster / Replication",
 "tags": [
  "kafka",
  "broker",
  "replication"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Env",
    "query": "label_values(kafka_server_brokerstate, env)"
   }
  ]
 },
 "panels": [
  {
   "title": "Replication BytesIn/Sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "kafka_server_broker_topic_metrics_ReplicationBytesInPerSec_rate{aggregate=\"OneMinute\",env=\"$env\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Replication BytesOut/Sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "kafka_server_broker_topic_metrics_ReplicationBytesOutPerSec_rate{aggregate=\"OneMinute\",env=\"$env\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Replication Max Lag Per Broker",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_server_replica_fetcher_manager_MaxLag_value{env=\"$env\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Fetch Bytes/sec Per Replication thread",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "kafka_server_fetcher_stats_BytesPerSec{env=\"$env\", aggregate=\"OneMinute\"}",
     "legendFormat": "Host {{job}}:{{broker_port}}, client_id={{client_id}}"
    }
   ]
  },
  {
   "title": "Fetch Requests/sec Per Replication thread",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "kafka_server_fetcher_stats_RequestsPerSec{env=\"$env\", aggregate=\"OneMinute\"}",
     "legendFormat": "Host {{job}}:{{broker_port}}, client_id={{client_id}}"
    }
   ]
  }
 ]
}