{
 "title": "Producer Performance",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "client_id",
    "query": {
     "query": "label_values(org_apache_kafka_producer_request_rate,client_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Producer request rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "wps" } },
     "targets": [
      {
       "expr": "org_apache_kafka_producer_request_rate{client_id=\"$client_id\"}",
       "legendFormat": "Request rate"
      }
     ]
    },
    {
     "title": "Producer record send rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "wps" } },
     "targets": [
      {
       "expr": "org_apache_kafka_producer_record_send_rate{client_id=\"$client_id\"}",
       "legendFormat": "Record send rate"
      }
     ]
    },
    {
     "title": "Producer batch size avg",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "org_apache_kafka_producer_batch_size_avg{client_id=\"$client_id\"}",
       "legendFormat": "Batch Size"
      }
     ]
    },
    {
     "title": "Producer topic byte rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "org_apache_kafka_producer_topic_byte_rate{client_id=\"$client_id\"}",
       "legendFormat": "{{topic}}"
      }
     ]
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Latencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "org_apache_kafka_producer_request_latency_avg{client_id=\"$client_id\"}",
     "legendFormat": "Avg Latency"
    },
    {
     "expr": "org_apache_kafka_producer_request_latency_max{client_id=\"$client_id\"}",
     "legendFormat": "Max latency"
    }
   ]
  },
  {
   "title": "IO ratio vs IO wait ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "org_apache_kafka_producer_io_ratio{client_id=\"$client_id\"}",
     "legendFormat": "IO ratio"
    },
    {
     "expr": "org_apache_kafka_producer_io_wait_ratio{client_id=\"$client_id\"}",
     "legendFormat": "IO wait ratio"
    }
   ]
  },
  {
   "title": "Node Request Latency Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "org_apache_kafka_producer_node_request_latency_avg{client_id=\"$client_id\"}",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Record Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "wps" } },
     "targets": [
      {
       "expr": "org_apache_kafka_producer_record_error_rate{client_id=\"$client_id\"}",
       "legendFormat": "Error Rate"
      }
     ]
    }
   ]
  }
 ]
}