/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.14.2/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    id("com.github.johnrengelman.shadow") version "8.1.1"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation("org.slf4j:slf4j-simple:2.0.7")
    implementation("io.opentelemetry.proto:opentelemetry-proto:1.0.0-alpha")
    implementation("io.grpc:grpc-api:1.66.0")
    implementation("io.grpc:grpc-netty-shaded:1.66.0")
    implementation("io.grpc:grpc-protobuf:1.66.0")
    implementation("io.grpc:grpc-stub:1.66.0")
    implementation("org.apache.kafka:kafka-clients:4.0.0")
}

tasks.shadowJar {
    archiveBaseName.set("metrics-reporter")
    archiveClassifier.set("") // This removes the "-all" suffix from the jar name
    mergeServiceFiles() // Merge service files from dependencies
    
    // Optional: Add a manifest with main class if this is an executable jar
    manifest {
        attributes["Implementation-Title"] = project.name
        attributes["Implementation-Version"] = project.version
        // Uncomment and set if you have a main class:
        // attributes["Main-Class"] = "org.example.Main"
    }
    
    // Optional: Exclude certain files if needed
    exclude("META-INF/*.SF")
    exclude("META-INF/*.DSA")
    exclude("META-INF/*.RSA")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.build {
    dependsOn(tasks.shadowJar)
}